---
- hosts: master
  vars:
    prometheus_url: https://github.com/prometheus/prometheus/releases/download/v2.3.1/prometheus-2.3.1.linux-amd64.tar.gz
  tasks:
  - name: download prometheus
    get_url:
      url: "{{ prometheus_url }}"
      dest: ~/

  - name: extract prometheus archive
    unarchive: src=~/prometheus-2.3.1.linux-amd64.tar.gz
               dest=~/
               copy=no

  - name: copy prometheus file
    shell: "cp ~/the_prom/prometheus.config ~/prometheus-2.3.1.linux-amd64/"

  - name: kill previous prometheus
    shell: "pkill -2 prometheus"
    ignore_errors: yes

  - name: start prometheus
    shell: "nohup ~/prometheus-2.3.1.linux-amd64/prometheus </dev/null >/dev/null 2>&1 &"

- hosts: slaves
  vars:
    node_url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    node_tar: ~/node_exporter-0.16.0.linux-amd64.tar.gz
    node_directory: node_exporter-0.16.0.linux-amd64
  tasks:
  - name: kill previous node exporter process
    shell: "pkill node_exporter"
    ignore_errors: yes

  - name: download node exporter
    get_url:
      url: "{{ node_url }}"
      dest: ~/

  - name: extract node archive
    unarchive: src=~/node_exporter-0.16.0.linux-amd64.tar.gz
               dest=~/
               copy=no

  - name: start node exporter
    shell: "nohup ~/{{ node_directory }}/node_exporter </dev/null >/dev/null 2>&1 &"

