---
- hosts: master
  vars:
    prometheus_url: https://github.com/prometheus/prometheus/releases/download/v2.3.1/prometheus-2.3.1.linux-amd64.tar.gz
    skip_all: false
  tasks:
  - name: kill previous prometheus
    shell: "pkill -2 prometheus"
    ignore_errors: yes
    when: not skip_all

  - name: download prometheus
    get_url:
      url: "{{ prometheus_url }}"
      dest: ~/
    when: not skip_all

  - name: extract prometheus archive
    unarchive: src=~/prometheus-2.3.1.linux-amd64.tar.gz
               dest=~/
               copy=no
    when: not skip_all

  - name: copy prometheus file
    shell: "cp ~/the_prom/prometheus.config ~/prometheus-2.3.1.linux-amd64/"
    # when: not skip_all

  - name: start prometheus
    shell: "cd ~/prometheus-2.3.1.linux-amd64; nohup ./prometheus --config.file=prometheus.config </dev/null >/dev/null 2>&1 &"
    when: not skip_all

- hosts: slaves
  vars:
    node_url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    node_tar: ~/node_exporter-0.16.0.linux-amd64.tar.gz
    node_directory: node_exporter-0.16.0.linux-amd64
    skip_all: false
  tasks:
  - name: kill previous node exporter process
    shell: "pkill node_exporter"
    ignore_errors: yes
    when: not skip_all

  - name: download node exporter
    get_url:
      url: "{{ node_url }}"
      dest: ~/
    when: not skip_all

  - name: extract node archive
    unarchive: src=~/node_exporter-0.16.0.linux-amd64.tar.gz
               dest=~/
               copy=no
    when: not skip_all

  - name: start node exporter
    shell: "nohup ~/{{ node_directory }}/node_exporter </dev/null >/dev/null 2>&1 &"
    when: not skip_all

  - name: install pip dependency
    yum:
      name: epel-release
      state: latest
    become: yes
    when: not skip_all

  - name: install pip
    yum:
      name: python-pip
      state: latest
    become: yes
    when: not skip_all

  - name: install prometheus_client for python
    pip:
      name: prometheus_client
    become: yes
    when: not skip_all

  - name: kill previous node exporter process
    shell: "pkill python"
    ignore_errors: yes

  - name: copy example python example server script
    copy:
      src: ~/the_prom/server_example.py
      dest: ~/
      mode: 0400

  - name: start node exporter
    shell: "nohup python ~/server_example.py </dev/null >/dev/null 2>&1 &"